name: Cache write

runs:
  runs-on: ubuntu-latest

  steps:
    - name: List files
      run: ls .

    - name: Write cache
      uses: actions/cache/save@v4
      with:
        key: cache-${{ github.run_id }}-${{ github.run_attempt }}
        path: example-data.json
