name: Cache write
description: Write the local data to the cache.

runs:
  using: 'composite'

  steps:
    - name: List files
      shell: bash
      run: ls .

    - name: Write cache
      uses: actions/cache/save@v4
      with:
        key: cache-${{ github.run_id }}-${{ github.run_attempt }}
        path: example-data.json
