name: Read cache
description: Read the cache data, when present.

runs:
  using: 'composite'

  steps:
    - name: Read cache
      uses: actions/cache/restore@v4
      with:
        key: cache-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./*.json
        restore-keys: |
          cache-
