name: Square Numbers

on:
  workflow_dispatch:
  push:

jobs:
  square:
    name: Square
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore cache
        uses: ./.github/workflows/cache-read

      - name: Square the value
        run: node square.mjs

      - name: Save cache
        uses: ./.github/workflows/cache-write
